### ISSUE TITLE
Running error

### ISSUE THREAD

**Issue by HalfLemon** [lopuhin/kaggle-dstl#3]
Position:
       train.py->main()
       arg('--model-path',type=Path)
Question:
Could you tell me what to fill in here?  (  train_geojson_v3 ?)
if is 'train_geojson_v3',    it‘s error :No such file or directory: 'align_cache\\6010_1_2_p.alignment'

**Comment by lopuhin** [comment]
Maybe creating an empty ``align_cache`` directory will help? Sorry, this code expects some directories and data files and this is not documented at all.

**Comment by HalfLemon** [comment]
I followed the breakpoint and found it was 
   in utils.py
 115row:  cached_path=Path('align_cache').joinpath('{}.alignment'.format(key))
but there's no file 'align_cache'
could you help me? please...

**Comment by lopuhin** [comment]
Did you try creating the directory as I suggested above?

**Comment by HalfLemon** [comment]
thanks very much,  I'll just change this path to my own path. it is successful!

**Comment by lopuhin** [comment]
Glad you solved it!

**Comment by vaihav** [comment]
Hey lopuhin, Excellent work.

I am a beginner and learning through your work. Can you help me in which part of the code needs to be looked so that I can provide a new satellite image to predict outcomes as segmented images? Further, I can see there are around 20 bands in the images , How to go about if I have an image with three bands only and I want to do predictions on it.
Thanks,
Vaibhav
